repository:
  name: VoiceToTextPCF
  description: A Power Apps Component Framework (PCF) control that enables voice-to-text functionality using Web Speech API
  homepage: https://github.com/UmeshBharvad/VoiceToTextPCF
  topics:
    - powerapps
    - pcf
    - voice-to-text
    - speech-recognition
    - power-platform
    - typescript
    - react
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: question
    color: d876e3
    description: Further information is requested
  - name: accessibility
    color: 0e8a16
    description: Accessibility-related issues or improvements

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
      enforce_admins: false
      restrictions: null
